### PR TITLE
Enable noop precompile in x/evm params

### PR DESCRIPTION
**Pull request by evgeniy-scherbina**

### CODE REVIEW

**Review by pirtleshell — COMMENTED** [review]
can you add your changes to the script [here](https://github.com/Kava-Labs/kvtool/blob/master/config/generate/genesis/generate-kava-genesis.sh)?

it works by installing the relevant version of kava locally and then running `make generate-kava-genesis`. this allows automatic pick up of new params and changes to default values while selectively overriding parts of the genesis file

**Comment by evgeniy-scherbina** [comment]
got it, will do

**Comment by evgeniy-scherbina** [comment]
> can you add your changes to the script [here](https://github.com/Kava-Labs/kvtool/blob/master/config/generate/genesis/generate-kava-genesis.sh)?
> 
> it works by installing the relevant version of kava locally and then running `make generate-kava-genesis`. this allows automatic pick up of new params and changes to default values while selectively overriding parts of the genesis file

**Comment by evgeniy-scherbina** [comment]
Fixed

**Review by pirtleshell — APPROVED** [review]

**Pull request merged**
